export interface ForumPost {
  id: string;
  username: string;
  userAvatar: string;
  timestamp: string;
  title: string;
  content: string;
  replies: number;
  likes: number;
}

export const forumPostsData: ForumPost[] = [
  {
    id: '1',
    username: 'hamzakhan3',
    userAvatar: 'https://i.pravatar.cc/150?u=hamzakhan3',
    timestamp: '2h ago',
    title: 'Hit 14 days clean - feeling amazing',
    content: 'Just wanted to share that I finally hit 2 weeks. The first few days were brutal but it gets easier. Stay strong everyone 💪',
    replies: 12,
    likes: 47,
  },
  {
    id: '2',
    username: 'tobywilson321',
    userAvatar: 'https://i.pravatar.cc/150?u=tobywilson321',
    timestamp: '5h ago',
    title: 'Need advice - struggling today',
    content: 'Day 4 here and the urges are hitting hard. Anyone have tips on what helps them get through the tough moments?',
    replies: 23,
    likes: 31,
  },
  {
    id: '3',
    username: 'lwayne453',
    userAvatar: 'https://i.pravatar.cc/150?u=lwayne453',
    timestamp: '1d ago',
    title: '90 days milestone reached! 🎉',
    content: 'Never thought I\'d make it this far. My confidence is back, relationships are better, and I actually feel motivated to work on my goals. Keep going, it\'s worth it!',
    replies: 56,
    likes: 184,
  },
  {
    id: '4',
    username: 'sl4ke765',
    userAvatar: 'https://i.pravatar.cc/150?u=sl4ke765',
    timestamp: '1d ago',
    title: 'Relapsed after 22 days but not giving up',
    content: 'Really disappointed in myself but I know I can\'t let this define me. Starting fresh tomorrow. Has anyone else bounced back from a relapse?',
    replies: 19,
    likes: 28,
  },
  {
    id: '5',
    username: 'marcus_r92',
    userAvatar: 'https://i.pravatar.cc/150?u=marcus_r92',
    timestamp: '2d ago',
    title: 'Cold showers are a game changer',
    content: 'Started taking cold showers every morning and it\'s helped so much with discipline and fighting urges. Highly recommend trying it!',
    replies: 34,
    likes: 89,
  },
  {
    id: '6',
    username: 'jayden_h07',
    userAvatar: 'https://i.pravatar.cc/150?u=jayden_h07',
    timestamp: '3d ago',
    title: 'Week 1 complete - here\'s what helped me',
    content: 'Made it through my first week! Key things: staying busy, working out daily, and avoiding phone at night. We got this 🔥',
    replies: 15,
    likes: 62,
  },
  {
    id: '7',
    username: 'dev_chronicles',
    userAvatar: 'https://i.pravatar.cc/150?u=dev_chronicles',
    timestamp: '4d ago',
    title: '100 days clean! Life update',
    content: 'Hit triple digits today. Lost 15lbs, got promoted at work, confidence is through the roof. Started dating again. Life is completely different. To anyone struggling - it\'s so worth it. AMA',
    replies: 67,
    likes: 312,
  },
  {
    id: '9',
    username: 'alex_rivera23',
    userAvatar: 'https://i.pravatar.cc/150?u=alex_rivera23',
    timestamp: '5d ago',
    title: 'Question: How to handle social media triggers?',
    content: 'Every time I open Instagram or TikTok, I see triggering content. The algorithm seems to know exactly what to show me. How do you guys deal with this? Deleting the apps seems extreme but maybe that\'s the answer?',
    replies: 37,
    likes: 54,
  },
  {
    id: '10',
    username: 'chris_morales',
    userAvatar: 'https://i.pravatar.cc/150?u=chris_morales',
    timestamp: '6d ago',
    title: 'Relapsed but learned something important',
    content: 'Made it 22 days then relapsed last night. But I figured out my trigger - boredom + being alone at night. Now I know what to watch for. Progress not perfection right?',
    replies: 41,
    likes: 76,
  },
  {
    id: '11',
    username: 'jordan_smith88',
    userAvatar: 'https://i.pravatar.cc/150?u=jordan_smith88',
    timestamp: '6d ago',
    title: 'Started lifting weights - game changing',
    content: 'Been doing this recovery thing for 2 months. Started hitting the gym 5 days ago and it\'s made SUCH a difference. The discipline, the endorphins, the confidence boost. If you\'re not working out yet, START. What\'s your workout routine?',
    replies: 52,
    likes: 143,
  },
  {
    id: '12',
    username: 'tyler_nguyen',
    userAvatar: 'https://i.pravatar.cc/150?u=tyler_nguyen',
    timestamp: '1w ago',
    title: 'Question: When does sleep quality improve?',
    content: 'I\'m on day 18 and still sleeping terribly. Tossing and turning, waking up multiple times. For those who\'ve been at this longer - when did your sleep get better? Or does it not improve?',
    replies: 34,
    likes: 41,
  },
  {
    id: '13',
    username: 'omar_hassan',
    userAvatar: 'https://i.pravatar.cc/150?u=omar_hassan',
    timestamp: '1w ago',
    title: 'When does brain fog clear up?',
    content: 'Day 25 here. Still struggling with concentration and memory. Can\'t focus at work, forgetting things constantly. Is this normal? When did you guys notice mental clarity returning?',
    replies: 28,
    likes: 39,
  },
  {
    id: '14',
    username: 'adrian_costa',
    userAvatar: 'https://i.pravatar.cc/150?u=adrian_costa',
    timestamp: '1w ago',
    title: 'How do I tell my partner about my addiction?',
    content: 'Been dating my girlfriend for 6 months. She doesn\'t know about my struggle. I\'m 35 days clean and want to be honest with her but terrified. How did you guys approach this conversation?',
    replies: 45,
    likes: 67,
  },
];
