export interface KnowledgeFeedItem {
  id: string;
  type: 'blog' | 'book' | 'research' | 'article' | 'embedded' | 'ai-summary';
  title: string;
  summary: string;
  author?: string;
  source?: string;
  url?: string;
  readMoreUrl?: string;
  date: string;
  tags?: string[];
  category: 'mindset' | 'science' | 'motivation' | 'success-stories' | 'practical';
  imageUrl?: string;
  fullContent?: string;
  isAISummary?: boolean;
  originalSourceUrl?: string;
}

export const knowledgeFeedData: KnowledgeFeedItem[] = [
  {
    id: 'kf1',
    type: 'research',
    category: 'science',
    title: 'The Neuroscience of Habit Formation',
    summary: 'Research shows that habit formation involves the basal ganglia, a part of the brain associated with emotions, patterns, and memories. When you repeat an action consistently, neural pathways strengthen, making the behavior automatic. This process typically takes 66 days on average to form a new habit. Understanding this helps in recovery: every day you resist strengthens new, healthier neural pathways.',
    author: 'Dr. Phillippa Lally',
    source: 'European Journal of Social Psychology',
    readMoreUrl: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/ejsp.674',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 0).toISOString(),
    tags: ['neuroscience', 'habits', 'research'],
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80',
  },
  {
    id: 'kf2',
    type: 'book',
    category: 'mindset',
    title: 'Atomic Habits - The Power of Tiny Changes',
    summary: 'James Clear explains that improving by just 1% every day compounds into remarkable results over time. The key is not to focus on goals, but on systems. In recovery, this means building daily routines and environments that make success inevitable. Small habits like morning exercise, cold showers, or meditation stack up to create lasting transformation.',
    author: 'James Clear',
    source: 'Atomic Habits',
    readMoreUrl: 'https://jamesclear.com/atomic-habits',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    tags: ['habits', 'self-improvement', 'systems'],
    imageUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&q=80',
  },
  {
    id: 'kf3',
    type: 'blog',
    category: 'science',
    title: 'Understanding Dopamine and Recovery',
    summary: 'Dopamine is often misunderstood as the "pleasure chemical," but it\'s actually about motivation and reward anticipation. Excessive pornography consumption floods your brain with dopamine, desensitizing receptors over time. This leads to needing more extreme content for the same effect. The good news: dopamine receptors can heal. Studies show significant recovery in just 90 days of abstinence.',
    author: 'Gary Wilson',
    source: 'Your Brain on Porn',
    readMoreUrl: 'https://yourbrainonporn.com',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    tags: ['dopamine', 'neuroscience', 'recovery'],
    imageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800&q=80',
  },
  {
    id: 'kf4',
    type: 'article',
    category: 'practical',
    title: 'The Role of Triggers in Relapse',
    summary: 'Triggers are environmental or emotional cues that activate cravings. Common triggers include stress, boredom, loneliness, and certain times of day. The key to managing triggers is awareness and having a prepared response. Create a trigger journal: identify what leads to urges, then develop specific counter-actions for each trigger. This transforms reactive behavior into proactive management.',
    author: 'Dr. Patrick Carnes',
    source: 'Psychology Today',
    readMoreUrl: 'https://www.psychologytoday.com',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    tags: ['triggers', 'awareness', 'strategy'],
    imageUrl: 'https://images.unsplash.com/photo-1499728603263-13726abce5fd?w=800&q=80',
  },
  {
    id: 'kf5',
    type: 'book',
    category: 'mindset',
    title: 'The Power of Now - Living in the Present',
    summary: 'Eckhart Tolle teaches that most suffering comes from dwelling on the past or fearing the future. Urges are temporary mental states that pass when you don\'t engage with them. Practice observing urges without judgment: "I notice I\'m having an urge." This creates distance between you and the impulse, making it easier to let it pass without acting on it.',
    author: 'Eckhart Tolle',
    source: 'The Power of Now',
    readMoreUrl: 'https://www.eckharttolle.com',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    tags: ['mindfulness', 'present-moment', 'awareness'],
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80',
  },
  {
    id: 'kf6',
    type: 'research',
    category: 'practical',
    title: 'Exercise as a Recovery Tool',
    summary: 'Multiple studies confirm that regular exercise significantly reduces cravings and improves mood regulation. Physical activity increases BDNF (Brain-Derived Neurotrophic Factor), which helps repair and grow new neural connections. Even 20 minutes of moderate exercise can reduce urges by up to 50%. Exercise also improves sleep quality, which is crucial for recovery.',
    author: 'Dr. John Ratey',
    source: 'Harvard Medical School',
    readMoreUrl: 'https://www.health.harvard.edu',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    tags: ['exercise', 'neuroscience', 'recovery'],
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80',
  },
  {
    id: 'kf7',
    type: 'blog',
    category: 'science',
    title: 'The Chaser Effect Explained',
    summary: 'After a relapse, many experience the "chaser effect" - a surge of cravings for several days. This happens because your brain temporarily remembers the dopamine spike and wants more. Understanding this is crucial: the first few days after a relapse are the hardest, but they don\'t represent your baseline. Push through 3-7 days and cravings significantly decrease.',
    author: 'NoFap Community',
    source: 'NoFap.com',
    readMoreUrl: 'https://nofap.com',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
    tags: ['recovery', 'relapse', 'understanding'],
    imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80',
  },
  {
    id: 'kf8',
    type: 'article',
    category: 'mindset',
    title: 'Building Self-Compassion in Recovery',
    summary: 'Research by Dr. Kristin Neff shows that self-compassion is more effective than self-criticism for behavior change. When you relapse, beating yourself up activates stress responses that make further relapses more likely. Instead, practice self-compassion: acknowledge the mistake, recognize you\'re human, and commit to learning from it. This creates psychological safety for growth.',
    author: 'Dr. Kristin Neff',
    source: 'Self-Compassion Research',
    readMoreUrl: 'https://self-compassion.org',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    tags: ['self-compassion', 'psychology', 'growth'],
    imageUrl: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=800&q=80',
  },
  {
    id: 'kf9',
    type: 'book',
    category: 'motivation',
    title: 'Man\'s Search for Meaning - Finding Purpose',
    summary: 'Viktor Frankl teaches that those who have a strong "why" can endure any "how." In recovery, connecting to your deeper purpose makes resisting urges meaningful rather than just restrictive. Ask yourself: What kind of person do I want to become? What relationships do I want to improve? How do I want to feel? These answers become your north star in difficult moments.',
    author: 'Viktor Frankl',
    source: 'Man\'s Search for Meaning',
    readMoreUrl: 'https://www.viktorfranklstore.com',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    tags: ['purpose', 'meaning', 'philosophy'],
    imageUrl: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&q=80',
  },
  {
    id: 'kf10',
    type: 'research',
    category: 'practical',
    title: 'Sleep and Willpower Connection',
    summary: 'Studies show that sleep deprivation significantly reduces prefrontal cortex activity - the part of your brain responsible for impulse control and decision-making. Getting less than 7 hours of sleep can reduce willpower by up to 30%. Prioritizing sleep is not optional in recovery; it\'s a foundational requirement. Establish a consistent sleep schedule and protect it fiercely.',
    author: 'Dr. Matthew Walker',
    source: 'Why We Sleep',
    readMoreUrl: 'https://www.sleepdiplomat.com',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
    tags: ['sleep', 'willpower', 'neuroscience'],
    imageUrl: 'https://images.unsplash.com/photo-1541480551145-2370a440d585?w=800&q=80',
  },
  {
    id: 'kf11',
    type: 'blog',
    category: 'practical',
    title: 'The 90-Day Reboot Timeline',
    summary: 'Many report following a predictable recovery timeline: Days 1-7: Withdrawal symptoms, mood swings, irritability. Days 7-14: Flatline may begin - reduced libido and motivation. Days 14-30: Energy returns, confidence grows. Days 30-60: More stable mood, clearer thinking. Days 60-90: Significant brain healing, renewed interest in life. Remember: everyone\'s timeline varies, but improvements are coming.',
    author: 'Recovery Community',
    source: 'NoFap Community Research',
    readMoreUrl: 'https://nofap.com',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    tags: ['timeline', 'recovery', 'expectations'],
    imageUrl: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&q=80',
  },
  {
    id: 'kf12',
    type: 'article',
    category: 'practical',
    title: 'Cold Showers and Resilience Training',
    summary: 'Cold exposure has been shown to increase dopamine by 250% and improve mood regulation. More importantly, voluntarily doing something uncomfortable trains your brain to overcome resistance - the same skill needed to resist urges. Start with 30 seconds of cold water at the end of your shower. This daily practice builds mental toughness that transfers to all areas of life.',
    author: 'Dr. Andrew Huberman',
    source: 'Huberman Lab Podcast',
    readMoreUrl: 'https://hubermanlab.com',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 11).toISOString(),
    tags: ['resilience', 'dopamine', 'discipline'],
    imageUrl: 'https://images.unsplash.com/photo-1520458236925-c6b2f829f523?w=800&q=80',
  },
  {
    id: 'kf13',
    type: 'book',
    category: 'science',
    title: 'The Porn Trap - Understanding Escalation',
    summary: 'Dr. Wendy Maltz explains the progressive nature of porn use: what once satisfied becomes boring, leading to seeking more extreme content. This isn\'t about moral failing; it\'s basic neuroscience - tolerance builds and stronger stimuli are needed. Recovery reverses this process. Your brain recalibrates to find pleasure in normal, healthy experiences again. Real intimacy becomes satisfying.',
    author: 'Dr. Wendy Maltz',
    source: 'The Porn Trap',
    readMoreUrl: 'https://www.healthysex.com',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    tags: ['understanding', 'recovery', 'neuroscience'],
    imageUrl: 'https://images.unsplash.com/photo-1527689368864-3a821dbccc34?w=800&q=80',
  },
  {
    id: 'kf14',
    type: 'research',
    category: 'motivation',
    title: 'Social Connection and Recovery Success',
    summary: 'Harvard\'s 80-year longitudinal study found that strong relationships are the single biggest predictor of happiness and health. In recovery, isolation is dangerous. Connecting with others - whether through support groups, therapy, or honest conversations with friends - dramatically improves success rates. You don\'t have to share everything, but don\'t carry this burden alone.',
    author: 'Dr. Robert Waldinger',
    source: 'Harvard Study of Adult Development',
    readMoreUrl: 'https://www.adultdevelopmentstudy.org',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 13).toISOString(),
    tags: ['social', 'connection', 'support'],
    imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80',
  },
  {
    id: 'kf15',
    type: 'blog',
    category: 'practical',
    title: 'Urge Surfing: Riding the Wave',
    summary: 'Urges follow a predictable pattern: they build like a wave, peak, then naturally subside - usually within 15-30 minutes. The technique of "urge surfing" involves observing the urge with curiosity rather than fighting it. Notice where you feel it in your body, watch it rise and fall, breathe through it. By not engaging, you prove to your brain that urges are manageable and temporary.',
    author: 'Dr. G. Alan Marlatt',
    source: 'Mindfulness-Based Relapse Prevention',
    readMoreUrl: 'https://www.mindfulrp.com',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    tags: ['techniques', 'mindfulness', 'urges'],
    imageUrl: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=800&q=80',
  },
  {
    id: 'kf16',
    type: 'embedded',
    category: 'success-stories',
    title: 'How I Broke Free After 10 Years',
    summary: 'A personal journey from addiction to recovery. This member shares the specific strategies that worked, the pitfalls to avoid, and the unexpected benefits of a porn-free life. "The first 30 days were brutal, but by day 90, I felt like a completely different person. My relationships improved, my confidence soared, and I rediscovered passions I\'d forgotten about."',
    author: 'Anonymous Member',
    source: 'Community Stories',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    tags: ['success', 'personal-story', 'inspiration'],
    imageUrl: 'https://images.unsplash.com/photo-1519834785169-98be25ec3f84?w=800&q=80',
    fullContent: 'Full article content would be here. This is where longer embedded content lives that users can read in-app without leaving.',
  },
  {
    id: 'kf17',
    type: 'ai-summary',
    category: 'science',
    title: 'How Neuroplasticity Enables Recovery',
    summary: 'AI Summary: Recent neuroscience research demonstrates that the brain\'s neuroplasticity allows for significant recovery from porn addiction. Studies show that abstinence leads to increased gray matter density in the prefrontal cortex, improved executive function, and restored dopamine sensitivity. The process takes time, but the brain physically rebuilds itself through consistent behavior change.',
    author: 'AI Generated from Multiple Sources',
    source: 'Neuroscience Journal Compilation',
    readMoreUrl: 'https://www.nature.com/subjects/neuroplasticity',
    originalSourceUrl: 'https://www.nature.com/subjects/neuroplasticity',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 16).toISOString(),
    tags: ['neuroplasticity', 'brain-healing', 'science'],
    imageUrl: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=800&q=80',
    isAISummary: true,
  },
  {
    id: 'kf18',
    type: 'embedded',
    category: 'motivation',
    title: 'The Benefits You Can Expect',
    summary: 'Based on thousands of recovery stories, here are the most commonly reported benefits: increased energy and motivation, better focus and concentration, improved relationships and social confidence, enhanced emotional regulation, better sleep quality, increased productivity, and a renewed sense of purpose. Most benefits become noticeable within 30-90 days.',
    author: 'Recovery Research Team',
    source: 'Community Data Analysis',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 17).toISOString(),
    tags: ['benefits', 'motivation', 'expectations'],
    imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80',
    fullContent: 'Detailed breakdown of benefits and timeline...',
  },
  {
    id: 'kf19',
    type: 'ai-summary',
    category: 'practical',
    title: 'Evidence-Based Strategies That Work',
    summary: 'AI Summary: Meta-analysis of addiction recovery studies reveals the most effective strategies: 1) Environmental modification (removing triggers), 2) Replacement behaviors (exercise, hobbies), 3) Social accountability (support groups), 4) Mindfulness practices (meditation, urge surfing), 5) Professional therapy (CBT, DBT), and 6) Physical health optimization (sleep, nutrition, exercise). Combining multiple strategies increases success rates significantly.',
    author: 'AI Generated from Research',
    source: 'Medical Journal Synthesis',
    readMoreUrl: 'https://www.ncbi.nlm.nih.gov/pmc/articles/',
    originalSourceUrl: 'https://www.ncbi.nlm.nih.gov/pmc/',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 18).toISOString(),
    tags: ['strategies', 'evidence-based', 'recovery'],
    imageUrl: 'https://images.unsplash.com/photo-1516534775068-ba3e7458af70?w=800&q=80',
    isAISummary: true,
  },
  {
    id: 'kf20',
    type: 'embedded',
    category: 'success-stories',
    title: 'From Shame to Self-Respect',
    summary: 'One member\'s powerful transformation story: "I lived in constant shame for years, hiding my addiction from everyone I loved. Recovery wasn\'t just about quitting porn—it was about learning to face myself with honesty and compassion. Today, I\'m not just porn-free, I\'m genuinely proud of who I\'m becoming. If I can do this, anyone can."',
    author: 'Anonymous Member',
    source: 'Community Stories',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 19).toISOString(),
    tags: ['shame', 'transformation', 'hope'],
    imageUrl: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=800&q=80',
    fullContent: 'Full personal story with detailed recovery journey...',
  },
];
