export interface ThreadReply {
  id: string;
  author: string;
  content: string;
  timestamp: string;
}

export const threadRepliesData: Record<string, ThreadReply[]> = {
  '1': [
    { id: '1-1', author: 'connor_j88', content: 'Congratulations bro! This is exactly what I needed to see today. Day 3 here and struggling but posts like this give me hope 💪', timestamp: '1h ago' },
    { id: '1-2', author: 'mike_fitness23', content: 'Massive W! What was the biggest change you noticed in yourself?', timestamp: '2h ago' },
    { id: '1-3', author: 'samuel_k91', content: 'So proud of you man. I relapsed yesterday after 18 days but this motivates me to start again. How did you push through the tough days?', timestamp: '3h ago' },
    { id: '1-4', author: 'ryan_beats', content: 'Legend! This community is incredible. Keep it up everyone 🔥', timestamp: '4h ago' },
    { id: '1-5', author: 'oliver_tech', content: 'Amazing work! Did you notice any changes in your confidence or energy levels?', timestamp: '5h ago' },
    { id: '1-6', author: 'tyler_m45', content: 'I\'m on day 8 and this gives me so much motivation!', timestamp: '6h ago' },
    { id: '1-7', author: 'jordan_lee', content: 'Keep pushing man, you\'re an inspiration', timestamp: '7h ago' },
    { id: '1-8', author: 'daniel_h32', content: 'What helped you the most during the first week?', timestamp: '8h ago' },
    { id: '1-9', author: 'kevin_z89', content: 'This is what I needed to see today. Thank you for sharing', timestamp: '9h ago' },
    { id: '1-10', author: 'brian_smith', content: 'Congrats! How did you deal with the urges in the evening?', timestamp: '10h ago' },
    { id: '1-11', author: 'chris_walker', content: 'Proud of you bro! Keep it up', timestamp: '11h ago' },
    { id: '1-12', author: 'jason_r77', content: '30 days is huge! Well done mate', timestamp: '12h ago' },
  ],
  '2': [
    { id: '2-1', author: 'luke_anderson', content: 'Cold showers help me instantly. Just turn the shower to ice cold when you feel it coming.', timestamp: '30m ago' },
    { id: '2-2', author: 'noah_p88', content: 'Get outside immediately. Go for a walk, run, anything to change your environment.', timestamp: '45m ago' },
    { id: '2-3', author: 'ethan_king', content: 'I do 20 push-ups every time I get an urge. Tires me out and refocuses my mind.', timestamp: '1h ago' },
    { id: '2-4', author: 'mason_white', content: 'Delete social media apps from your phone. They\'re the biggest trigger for me.', timestamp: '1h ago' },
    { id: '2-5', author: 'logan_davis', content: 'Call a friend or family member. Human connection helps a lot.', timestamp: '2h ago' },
    { id: '2-6', author: 'jackson_hill', content: 'Meditation app helped me understand my triggers better', timestamp: '2h ago' },
    { id: '2-7', author: 'aiden_scott', content: 'I write in my journal when urges hit. Helps process the feeling.', timestamp: '3h ago' },
    { id: '2-8', author: 'carter_green', content: 'Gym membership was the best investment for my recovery', timestamp: '3h ago' },
    { id: '2-9', author: 'wyatt_adams', content: 'Read motivational posts on this forum when struggling', timestamp: '4h ago' },
    { id: '2-10', author: 'dylan_baker', content: 'Keep your hands busy. I started learning guitar.', timestamp: '4h ago' },
    { id: '2-11', author: 'nathan_clark', content: 'The urges pass after 15-20 minutes if you just wait them out', timestamp: '5h ago' },
    { id: '2-12', author: 'caleb_lewis', content: 'Accountability partner changed everything for me', timestamp: '5h ago' },
    { id: '2-13', author: 'hunter_hall', content: 'I keep a list of reasons why I quit on my phone', timestamp: '6h ago' },
    { id: '2-14', author: 'austin_allen', content: 'Working out first thing in the morning sets the tone', timestamp: '6h ago' },
    { id: '2-15', author: 'justin_young', content: 'Turn off your phone and go to sleep if it\'s nighttime', timestamp: '7h ago' },
    { id: '2-16', author: 'brandon_king', content: 'I replaced the habit with reading books', timestamp: '7h ago' },
    { id: '2-17', author: 'zachary_wright', content: 'Prayer and meditation help me stay grounded', timestamp: '8h ago' },
    { id: '2-18', author: 'adam_lopez', content: 'The first 10 days are the hardest, push through!', timestamp: '8h ago' },
    { id: '2-19', author: 'sean_hill22', content: 'Keep a streak counter visible. Helps me not want to reset.', timestamp: '9h ago' },
    { id: '2-20', author: 'ian_torres', content: 'Yoga helped me with self-control more than I expected', timestamp: '9h ago' },
    { id: '2-21', author: 'gavin_rivera', content: 'Stay away from your bedroom during urges', timestamp: '10h ago' },
    { id: '2-22', author: 'colin_cook', content: 'I watch motivational speeches on YouTube', timestamp: '10h ago' },
    { id: '2-23', author: 'evan_morgan', content: 'Setting goals for the day keeps me focused', timestamp: '11h ago' },
    { id: '2-24', author: 'derek_bell', content: 'Cold exposure therapy is legit', timestamp: '11h ago' },
    { id: '2-25', author: 'marcus_reed', content: 'Join a sports team or group activity', timestamp: '12h ago' },
    { id: '2-26', author: 'travis_bailey', content: 'The pain of regret is worse than the pain of discipline', timestamp: '12h ago' },
    { id: '2-27', author: 'jeremy_cooper', content: 'I deleted all my triggers and started fresh', timestamp: '13h ago' },
    { id: '2-28', author: 'corey_richardson', content: 'Stay strong brother, you got this 💪', timestamp: '13h ago' },
  ],
  '3': [
    { id: '3-1', author: 'alex_garcia', content: 'This is so inspiring! Can\'t wait to hit this milestone myself', timestamp: '1h ago' },
    { id: '3-2', author: 'jacob_martinez', content: 'Day 45 here, this gives me hope to keep going', timestamp: '1h ago' },
    { id: '3-3', author: 'matthew_rodriguez', content: 'What was the biggest benefit you noticed?', timestamp: '2h ago' },
    { id: '3-4', author: 'andrew_wilson', content: 'Incredible achievement! So happy for you', timestamp: '2h ago' },
    { id: '3-5', author: 'joshua_taylor', content: 'This community is amazing. Posts like this keep me going', timestamp: '3h ago' },
    { id: '3-6', author: 'ryan_thomas', content: 'Did your social anxiety improve?', timestamp: '3h ago' },
    { id: '3-7', author: 'eric_jackson', content: 'You\'re a legend man! Keep it up', timestamp: '4h ago' },
    { id: '3-8', author: 'steven_white55', content: 'I\'m at day 12 and feeling the benefits already', timestamp: '4h ago' },
    { id: '3-9', author: 'kevin_harris', content: 'How did you handle flatline periods?', timestamp: '5h ago' },
    { id: '3-10', author: 'brian_martin', content: 'Saving this post for motivation', timestamp: '5h ago' },
    { id: '3-11', author: 'jason_thompson', content: 'Amazing! What\'s your daily routine like?', timestamp: '6h ago' },
    { id: '3-12', author: 'brandon_garcia', content: 'This is the push I needed today', timestamp: '6h ago' },
    { id: '3-13', author: 'adam_martinez', content: 'Congratulations! You earned it', timestamp: '7h ago' },
    { id: '3-14', author: 'justin_robinson', content: 'Day 7 here, can\'t wait to be where you are', timestamp: '7h ago' },
    { id: '3-15', author: 'tyler_clark', content: 'Respect! How did week 2-4 compare to the first week?', timestamp: '8h ago' },
    { id: '3-16', author: 'austin_lewis', content: 'Posts like these keep me accountable', timestamp: '8h ago' },
    { id: '3-17', author: 'zachary_lee', content: 'Did you notice improved focus at work/school?', timestamp: '9h ago' },
    { id: '3-18', author: 'lwayne453', content: 'Absolutely! Around day 30 I could focus for hours without getting distracted. Work productivity doubled.', timestamp: '9h ago' },
    { id: '3-19', author: 'sean_walker', content: '90 days is insane! Well done', timestamp: '9h ago' },
    { id: '3-20', author: 'matthew_rodriguez', content: 'When did the social anxiety start improving?', timestamp: '10h ago' },
    { id: '3-21', author: 'lwayne453', content: 'Around week 3-4. Eye contact became easier, conversations felt natural again. By week 8 it was basically gone.', timestamp: '10h ago' },
    { id: '3-22', author: 'kevin_harris', content: 'How did you push through the flatline?', timestamp: '10h ago' },
    { id: '3-23', author: 'lwayne453', content: 'Flatline hit around day 40-55. I just trusted the process and stayed busy. Working out and meditation helped a lot.', timestamp: '10h ago' },
    { id: '3-24', author: 'tyler_clark', content: 'That\'s exactly what I needed to hear. I\'m in flatline now.', timestamp: '11h ago' },
    { id: '3-25', author: 'jason_thompson', content: 'What does your daily routine look like?', timestamp: '11h ago' },
    { id: '3-26', author: 'lwayne453', content: 'Wake up 6am, cold shower, gym, healthy breakfast, work, read at night. Consistency is everything.', timestamp: '11h ago' },
    { id: '3-27', author: 'ryan_thomas', content: 'Cold showers are part of my routine too now!', timestamp: '12h ago' },
    { id: '3-28', author: 'eric_jackson', content: 'The confidence part is what I\'m most excited about', timestamp: '12h ago' },
    { id: '3-29', author: 'lwayne453', content: 'Confidence was the biggest change. I actually like who I am now.', timestamp: '12h ago' },
    { id: '3-30', author: 'justin_robinson', content: 'This thread is pure gold. Saving it.', timestamp: '13h ago' },
    { id: '3-31', author: 'andrew_wilson', content: 'Did you have any relapses before this streak?', timestamp: '13h ago' },
    { id: '3-32', author: 'lwayne453', content: 'Yeah, like 7-8 times over 6 months. Each relapse taught me what NOT to do.', timestamp: '13h ago' },
    { id: '3-33', author: 'jacob_martinez', content: 'That\'s encouraging. I\'ve relapsed twice already.', timestamp: '14h ago' },
    { id: '3-34', author: 'joshua_taylor', content: 'What was your biggest trigger?', timestamp: '14h ago' },
    { id: '3-35', author: 'lwayne453', content: 'Being alone at night with my phone. Now I charge it in another room.', timestamp: '14h ago' },
    { id: '3-36', author: 'alex_garcia', content: 'Smart move! I need to do that too.', timestamp: '15h ago' },
    { id: '3-37', author: 'steven_white55', content: 'What\'s your advice for someone on day 12?', timestamp: '15h ago' },
    { id: '3-38', author: 'lwayne453', content: 'The first 2 weeks are the hardest. Just survive them. It gets easier after day 14.', timestamp: '15h ago' },
    { id: '3-39', author: 'brian_martin', content: 'I\'m on day 13. This gives me hope.', timestamp: '16h ago' },
    { id: '3-40', author: 'adam_martinez', content: 'Did your relationships with family improve?', timestamp: '16h ago' },
    { id: '3-41', author: 'lwayne453', content: 'Massively. I actually connect with people now instead of isolating.', timestamp: '16h ago' },
    { id: '3-42', author: 'austin_lewis', content: 'The isolation was killing me. Can\'t wait to feel normal again.', timestamp: '17h ago' },
    { id: '3-43', author: 'zachary_lee', content: 'How long until you felt like yourself again?', timestamp: '17h ago' },
    { id: '3-44', author: 'lwayne453', content: 'Around day 60. That\'s when I looked in the mirror and recognized myself.', timestamp: '17h ago' },
    { id: '3-45', author: 'sean_walker', content: 'This is the most helpful thread I\'ve read. Thank you.', timestamp: '18h ago' },
    { id: '3-46', author: 'brandon_garcia', content: 'What would you tell someone thinking about quitting?', timestamp: '18h ago' },
    { id: '3-47', author: 'lwayne453', content: 'Just start. You don\'t need to be ready. The pain of staying the same is worse than the pain of change.', timestamp: '18h ago' },
    { id: '3-48', author: 'tyler_clark', content: 'That hit different. Starting today.', timestamp: '19h ago' },
    { id: '3-49', author: 'jason_thompson', content: 'We\'re all rooting for you!', timestamp: '19h ago' },
    { id: '3-50', author: 'kevin_harris', content: 'This community is the best support group', timestamp: '20h ago' },
    { id: '3-51', author: 'matthew_rodriguez', content: 'Did you journal during your journey?', timestamp: '20h ago' },
    { id: '3-52', author: 'lwayne453', content: 'Every single day. Helped me process emotions and track patterns.', timestamp: '20h ago' },
    { id: '3-53', author: 'ryan_thomas', content: 'I\'m going to start journaling tonight', timestamp: '21h ago' },
    { id: '3-54', author: 'brian_martin', content: 'What journal prompts did you use?', timestamp: '21h ago' },
    { id: '3-55', author: 'lwayne453', content: 'How I\'m feeling, what triggered me, what I\'m grateful for. Simple stuff.', timestamp: '21h ago' },
    { id: '3-56', author: 'eric_jackson', content: 'Grateful this post exists. You\'re changing lives.', timestamp: '22h ago' },
  ],
  '4': [
    { id: '4-1', author: 'michael_hall', content: 'I\'m on week 3 and sleep quality has been incredible', timestamp: '30m ago' },
    { id: '4-2', author: 'james_allen', content: 'Same! I used to wake up multiple times per night', timestamp: '1h ago' },
    { id: '4-3', author: 'william_young', content: 'How long did it take before you noticed the change?', timestamp: '1h ago' },
    { id: '4-4', author: 'david_king', content: 'This is one of the best benefits for sure', timestamp: '2h ago' },
    { id: '4-5', author: 'joseph_wright', content: 'Dreams became more vivid for me too', timestamp: '2h ago' },
    { id: '4-6', author: 'thomas_lopez', content: 'My sleep quality improved around day 10', timestamp: '3h ago' },
    { id: '4-7', author: 'charles_hill', content: 'No more late night scrolling was a game changer', timestamp: '3h ago' },
    { id: '4-8', author: 'christopher_scott', content: 'I fall asleep so much faster now', timestamp: '4h ago' },
    { id: '4-9', author: 'daniel_green', content: 'REM sleep quality definitely improved', timestamp: '4h ago' },
    { id: '4-10', author: 'paul_adams', content: 'Used to need 9 hours, now I feel great with 7', timestamp: '5h ago' },
    { id: '4-11', author: 'mark_baker', content: 'Mornings are so much easier now', timestamp: '5h ago' },
    { id: '4-12', author: 'donald_nelson', content: 'I wake up actually feeling rested', timestamp: '6h ago' },
    { id: '4-13', author: 'george_carter', content: 'This was one of the first benefits I noticed', timestamp: '6h ago' },
    { id: '4-14', author: 'kenneth_mitchell', content: 'Sleep tracking app shows huge improvement', timestamp: '7h ago' },
    { id: '4-15', author: 'steven_perez', content: 'No more brain fog in the morning!', timestamp: '7h ago' },
    { id: '4-16', author: 'edward_roberts', content: 'Deep sleep percentage went up significantly', timestamp: '8h ago' },
    { id: '4-17', author: 'brian_turner', content: 'I used to be exhausted all day, not anymore', timestamp: '8h ago' },
    { id: '4-18', author: 'ronald_phillips', content: 'This alone makes it worth it', timestamp: '9h ago' },
    { id: '4-19', author: 'anthony_campbell', content: 'Sleep is so underrated for recovery', timestamp: '9h ago' },
    { id: '4-20', author: 'kevin_parker', content: 'My Fitbit data shows massive improvement', timestamp: '10h ago' },
    { id: '4-21', author: 'jason_evans', content: 'Dreams feel more meaningful now', timestamp: '10h ago' },
    { id: '4-22', author: 'matthew_edwards', content: 'Insomnia completely gone for me', timestamp: '11h ago' },
    { id: '4-23', author: 'gary_collins', content: 'I actually enjoy going to bed now', timestamp: '11h ago' },
    { id: '4-24', author: 'timothy_stewart', content: 'Sleep schedule normalized naturally', timestamp: '12h ago' },
    { id: '4-25', author: 'jose_sanchez', content: 'Melatonin production must be better', timestamp: '12h ago' },
    { id: '4-26', author: 'larry_morris', content: 'Night sweats completely stopped', timestamp: '13h ago' },
    { id: '4-27', author: 'jeffrey_rogers', content: 'Feel like a new person in the mornings', timestamp: '13h ago' },
    { id: '4-28', author: 'frank_reed', content: 'This is one of the best benefits!', timestamp: '14h ago' },
    { id: '4-29', author: 'scott_cook', content: 'Energy levels throughout the day are better', timestamp: '14h ago' },
    { id: '4-30', author: 'eric_morgan', content: 'I wake up before my alarm now', timestamp: '15h ago' },
    { id: '4-31', author: 'stephen_bell', content: 'Quality over quantity for sure', timestamp: '15h ago' },
    { id: '4-32', author: 'andrew_murphy', content: 'This motivates me to keep going', timestamp: '16h ago' },
    { id: '4-33', author: 'raymond_bailey', content: 'Best sleep I\'ve had in years', timestamp: '16h ago' },
    { id: '4-34', author: 'gregory_rivera', content: 'Keep it up everyone! It\'s worth it', timestamp: '17h ago' },
  ],
  '5': [
    { id: '5-1', author: 'benjamin_cooper', content: 'Don\'t be too hard on yourself. Progress isn\'t linear', timestamp: '20m ago' },
    { id: '5-2', author: 'samuel_richardson', content: 'I relapsed 4 times before my current 60 day streak', timestamp: '40m ago' },
    { id: '5-3', author: 'patrick_cox', content: 'Identifying triggers is huge. You\'ve already won by learning', timestamp: '1h ago' },
    { id: '5-4', author: 'alexander_howard', content: 'What are you planning to do differently this time?', timestamp: '1h ago' },
    { id: '5-5', author: 'jack_ward', content: 'Boredom is my trigger too. Started reading books to fight it', timestamp: '2h ago' },
    { id: '5-6', author: 'ryan_torres', content: '22 days is still amazing progress. Don\'t forget that', timestamp: '2h ago' },
    { id: '5-7', author: 'jeremy_peterson', content: 'Every relapse taught me something valuable', timestamp: '3h ago' },
    { id: '5-8', author: 'nicholas_gray', content: 'The fact you\'re analyzing it means you\'re growing', timestamp: '3h ago' },
    { id: '5-9', author: 'walter_ramirez', content: 'Keep a boredom emergency list - activities to do immediately', timestamp: '4h ago' },
    { id: '5-10', author: 'peter_james', content: 'You got this bro. Learn and move forward', timestamp: '4h ago' },
    { id: '5-11', author: 'henry_watson', content: 'Setbacks are part of the journey. Don\'t quit', timestamp: '5h ago' },
    { id: '5-12', author: 'carl_brooks', content: 'I keep a list of things to do when bored on my phone', timestamp: '5h ago' },
    { id: '5-13', author: 'arthur_kelly', content: 'Have you tried scheduling your day in advance?', timestamp: '6h ago' },
    { id: '5-14', author: 'roger_sanders', content: 'Boredom + phone = danger zone for me too', timestamp: '6h ago' },
    { id: '5-15', author: 'joe_price', content: 'The learning is what matters. You\'ll beat this', timestamp: '7h ago' },
    { id: '5-16', author: 'albert_bennett', content: 'I had 5 relapses before hitting 90 days', timestamp: '7h ago' },
    { id: '5-17', author: 'jonathan_wood', content: 'Structure your free time better. That helped me', timestamp: '8h ago' },
    { id: '5-18', author: 'justin_barnes', content: 'You\'re not starting from zero. You learned something huge', timestamp: '8h ago' },
    { id: '5-19', author: 'terry_ross', content: 'Boredom was my biggest enemy too', timestamp: '9h ago' },
    { id: '5-20', author: 'gerald_henderson', content: 'Find a hobby that requires your full attention', timestamp: '9h ago' },
    { id: '5-21', author: 'keith_coleman', content: 'The awareness itself is huge progress', timestamp: '10h ago' },
    { id: '5-22', author: 'samuel_jenkins', content: 'Now you know what to watch for. That\'s powerful', timestamp: '10h ago' },
    { id: '5-23', author: 'willie_perry', content: 'I started gaming to fight boredom urges', timestamp: '11h ago' },
    { id: '5-24', author: 'ralph_powell', content: 'Keep your mind and hands busy', timestamp: '11h ago' },
    { id: '5-25', author: 'lawrence_long', content: 'You\'re going to crush it this time', timestamp: '12h ago' },
    { id: '5-26', author: 'philip_patterson', content: 'Learning from mistakes is the key to success', timestamp: '12h ago' },
    { id: '5-27', author: 'bobby_hughes', content: 'Schedule every hour of your day', timestamp: '13h ago' },
    { id: '5-28', author: 'johnny_flores', content: 'This is part of the process. Keep going', timestamp: '13h ago' },
    { id: '5-29', author: 'randy_washington', content: 'Have a plan for when boredom hits', timestamp: '14h ago' },
    { id: '5-30', author: 'howard_butler', content: 'You made it 22 days. You can do it again', timestamp: '14h ago' },
    { id: '5-31', author: 'eugene_simmons', content: 'Boredom is just an opportunity to build discipline', timestamp: '15h ago' },
    { id: '5-32', author: 'carlos_foster', content: 'I keep gym clothes ready for boredom moments', timestamp: '15h ago' },
    { id: '5-33', author: 'russell_gonzales', content: 'Recognizing patterns is the first step to breaking them', timestamp: '16h ago' },
    { id: '5-34', author: 'bobby_bryant', content: 'Cold showers when bored help me reset', timestamp: '16h ago' },
    { id: '5-35', author: 'victor_alexander', content: 'You\'ve got the self-awareness now', timestamp: '17h ago' },
    { id: '5-36', author: 'ernest_russell', content: 'Fill your schedule with activities', timestamp: '17h ago' },
    { id: '5-37', author: 'phillip_griffin', content: 'Every attempt teaches you something new', timestamp: '18h ago' },
    { id: '5-38', author: 'todd_diaz', content: 'The fact you\'re back here shows your commitment', timestamp: '18h ago' },
    { id: '5-39', author: 'jesse_hayes', content: 'Boredom = time to do something productive', timestamp: '19h ago' },
    { id: '5-40', author: 'craig_myers', content: 'Stay strong brother. You learned the lesson', timestamp: '19h ago' },
    { id: '5-41', author: 'alan_ford', content: 'Next streak will be your best one yet', timestamp: '20h ago' },
  ],
  '6': [
    { id: '6-1', author: 'shawn_hamilton', content: 'Lifting weights changed my life too. Best decision', timestamp: '30m ago' },
    { id: '6-2', author: 'clarence_graham', content: 'What\'s your routine look like?', timestamp: '45m ago' },
    { id: '6-3', author: 'sean_sullivan', content: 'Started PPL split 3 months ago, game changer', timestamp: '1h ago' },
    { id: '6-4', author: 'philip_wallace', content: 'The discipline from gym transfers to everything else', timestamp: '1h ago' },
    { id: '6-5', author: 'johnny_woods', content: 'What time do you usually work out?', timestamp: '2h ago' },
    { id: '6-6', author: 'earl_kennedy', content: 'Morning workouts set the tone for my whole day', timestamp: '2h ago' },
    { id: '6-7', author: 'jimmy_parker22', content: 'Gains + mental clarity = unstoppable combo', timestamp: '3h ago' },
    { id: '6-8', author: 'antonio_lawson', content: 'Do you do cardio too or just weights?', timestamp: '3h ago' },
    { id: '6-9', author: 'danny_fields', content: 'The confidence boost from lifting is real', timestamp: '4h ago' },
    { id: '6-10', author: 'bryan_freeman', content: 'Started with 3 days, now doing 6. Addicted to the progress', timestamp: '4h ago' },
    { id: '6-11', author: 'tony_webb', content: 'Gym is like meditation for me now', timestamp: '5h ago' },
    { id: '6-12', author: 'luis_tucker', content: 'What\'s your go-to pre-workout?', timestamp: '5h ago' },
    { id: '6-13', author: 'mike_porter', content: 'Push/Pull/Legs or Upper/Lower split?', timestamp: '6h ago' },
    { id: '6-14', author: 'stanley_hunter', content: 'The pump is the best feeling', timestamp: '6h ago' },
    { id: '6-15', author: 'leonard_hicks', content: 'How long until you saw real progress?', timestamp: '7h ago' },
    { id: '6-16', author: 'nathan_crawford', content: 'Consistency is key. I\'m on month 4', timestamp: '7h ago' },
    { id: '6-17', author: 'manuel_henry', content: 'Progressive overload changed everything for me', timestamp: '8h ago' },
    { id: '6-18', author: 'rodney_boyd', content: 'The mental benefits are underrated', timestamp: '8h ago' },
    { id: '6-19', author: 'curtis_mason', content: 'Do you track your lifts?', timestamp: '9h ago' },
    { id: '6-20', author: 'norman_morales', content: 'Started tracking and progress doubled', timestamp: '9h ago' },
    { id: '6-21', author: 'allen_kennedy', content: 'Compound movements or isolation?', timestamp: '10h ago' },
    { id: '6-22', author: 'marvin_warren', content: 'Focus on compounds first, then isolation', timestamp: '10h ago' },
    { id: '6-23', author: 'vincent_dixon', content: 'Deadlifts and squats = king exercises', timestamp: '11h ago' },
    { id: '6-24', author: 'glenn_ramos', content: 'The pump addiction is real 💪', timestamp: '11h ago' },
    { id: '6-25', author: 'jeffery_gilbert', content: 'What\'s your favorite workout split?', timestamp: '12h ago' },
    { id: '6-26', author: 'travis_stone', content: 'Rest days are just as important!', timestamp: '12h ago' },
    { id: '6-27', author: 'chad_hawkins', content: 'Sleep + gym + nutrition = gains', timestamp: '13h ago' },
    { id: '6-28', author: 'jacob_dunn', content: 'Form over ego lifting always', timestamp: '13h ago' },
    { id: '6-29', author: 'melvin_perkins', content: 'Progressive overload is the secret', timestamp: '14h ago' },
    { id: '6-30', author: 'alfred_spencer', content: 'Lifting taught me discipline in all areas', timestamp: '14h ago' },
    { id: '6-31', author: 'kyle_peters', content: 'The mental health benefits are huge', timestamp: '15h ago' },
    { id: '6-32', author: 'francis_franklin', content: 'Started 6 months ago, down 30lbs', timestamp: '15h ago' },
    { id: '6-33', author: 'bradley_wright22', content: 'Consistency beats intensity every time', timestamp: '16h ago' },
    { id: '6-34', author: 'jesus_stephens', content: 'The gym saved my life honestly', timestamp: '16h ago' },
    { id: '6-35', author: 'herbert_ferguson', content: 'What\'s your bench/squat/deadlift numbers?', timestamp: '17h ago' },
    { id: '6-36', author: 'frederick_ford', content: 'Strength gains = confidence gains', timestamp: '17h ago' },
    { id: '6-37', author: 'ray_reynolds', content: 'Do you follow any specific program?', timestamp: '18h ago' },
    { id: '6-38', author: 'joel_ellis', content: 'Been running nSuns, highly recommend', timestamp: '18h ago' },
    { id: '6-39', author: 'edwin_harper', content: 'The routine keeps me accountable', timestamp: '19h ago' },
    { id: '6-40', author: 'don_fox', content: 'Gym = therapy + gains', timestamp: '19h ago' },
    { id: '6-41', author: 'ricky_alexander', content: 'Lost 40lbs and gained confidence', timestamp: '20h ago' },
    { id: '6-42', author: 'marc_hayes55', content: 'Muscle confusion or progressive overload?', timestamp: '20h ago' },
    { id: '6-43', author: 'nathaniel_gardner', content: 'Both have their place in training', timestamp: '21h ago' },
    { id: '6-44', author: 'clifford_wells', content: 'The discipline transfers to recovery journey', timestamp: '21h ago' },
    { id: '6-45', author: 'francis_hart', content: 'Working out kills urges for me', timestamp: '22h ago' },
    { id: '6-46', author: 'evan_mcdonald', content: 'Same! Endorphins help so much', timestamp: '22h ago' },
    { id: '6-47', author: 'jeffery_tucker', content: 'Leg day is the hardest but most rewarding', timestamp: '23h ago' },
    { id: '6-48', author: 'derek_andrews', content: 'Never skip leg day 🦵', timestamp: '23h ago' },
    { id: '6-49', author: 'austin_santiago', content: 'The gym community is amazing', timestamp: '1d ago' },
    { id: '6-50', author: 'seth_fuller', content: 'Gymbros supporting recovery, love it', timestamp: '1d ago' },
    { id: '6-51', author: 'marcus_sims', content: 'This post motivated me to sign up', timestamp: '1d ago' },
    { id: '6-52', author: 'isaac_foster', content: 'Best investment you can make. Let\'s go! 💪🔥', timestamp: '1d ago' },
  ],
  '7': [
    { id: '7-1', author: 'luke_bryant', content: 'I deleted Instagram completely. Best decision ever', timestamp: '30m ago' },
    { id: '7-2', author: 'gavin_alexander', content: 'Use content filters and block suggestions', timestamp: '1h ago' },
    { id: '7-3', author: 'wyatt_russell', content: 'Removed all social media from my phone', timestamp: '1h ago' },
    { id: '7-4', author: 'blake_griffin', content: 'The algorithm keeps pushing triggering content', timestamp: '2h ago' },
    { id: '7-5', author: 'owen_hayes', content: 'I only use social media on my laptop now', timestamp: '2h ago' },
    { id: '7-6', author: 'silas_myers', content: 'Deleted TikTok 2 months ago, life is better', timestamp: '3h ago' },
    { id: '7-7', author: 'landon_ford', content: 'Use screen time limits and content restrictions', timestamp: '3h ago' },
    { id: '7-8', author: 'sawyer_hamilton', content: 'The "Not Interested" button doesn\'t work for me either', timestamp: '4h ago' },
    { id: '7-9', author: 'parker_graham', content: 'I keep social media logged out on my phone', timestamp: '4h ago' },
    { id: '7-10', author: 'chase_sullivan', content: 'Explore page is the worst trigger', timestamp: '5h ago' },
    { id: '7-11', author: 'elias_wallace', content: 'Switched to Reddit only, way better control', timestamp: '5h ago' },
    { id: '7-12', author: 'emmett_woods', content: 'Use app blockers during vulnerable times', timestamp: '6h ago' },
    { id: '7-13', author: 'finn_kennedy', content: 'Grayscale mode on my phone helped reduce scrolling', timestamp: '6h ago' },
    { id: '7-14', author: 'rhett_lawson', content: 'Social media is designed to be addictive', timestamp: '7h ago' },
    { id: '7-15', author: 'cash_fields', content: 'I only follow educational accounts now', timestamp: '7h ago' },
    { id: '7-16', author: 'cruz_freeman', content: 'Deleted Snapchat too, it was bad', timestamp: '8h ago' },
    { id: '7-17', author: 'griffin_webb', content: 'The FOMO was hard at first but now I don\'t miss it', timestamp: '8h ago' },
    { id: '7-18', author: 'knox_tucker', content: 'Use parental controls on your own phone', timestamp: '9h ago' },
    { id: '7-19', author: 'kai_porter', content: 'I have my accountability partner manage my restrictions', timestamp: '9h ago' },
    { id: '7-20', author: 'duke_hunter', content: 'The algorithm knows exactly what to show you', timestamp: '10h ago' },
    { id: '7-21', author: 'miles_hicks', content: 'Cold turkey deletion worked for me', timestamp: '10h ago' },
    { id: '7-22', author: 'maddox_crawford', content: '30-day social media detox changed my life', timestamp: '11h ago' },
    { id: '7-23', author: 'brooks_henry', content: 'Use website blockers on all devices', timestamp: '11h ago' },
    { id: '7-24', author: 'beckett_boyd', content: 'Following only friends and family helps', timestamp: '12h ago' },
    { id: '7-25', author: 'king_mason', content: 'Turn off autoplay on all platforms', timestamp: '12h ago' },
    { id: '7-26', author: 'archer_morales', content: 'Delete and reinstall when you need it', timestamp: '13h ago' },
    { id: '7-27', author: 'reed_johnston', content: 'That\'s too much work, just delete permanently', timestamp: '13h ago' },
    { id: '7-28', author: 'braxton_dixon', content: 'Instagram reels are the worst', timestamp: '14h ago' },
    { id: '7-29', author: 'holden_ramos', content: 'Agreed! Endless scrolling is designed to trap you', timestamp: '14h ago' },
    { id: '7-30', author: 'maximus_gilbert', content: 'Use app timers and stick to them', timestamp: '15h ago' },
    { id: '7-31', author: 'zane_stone', content: 'Going outside more helped me forget about social media', timestamp: '15h ago' },
    { id: '7-32', author: 'atlas_hawkins', content: 'Reading replaced scrolling for me', timestamp: '16h ago' },
    { id: '7-33', author: 'jude_dunn', content: 'Best decision: deleting all of it', timestamp: '16h ago' },
    { id: '7-34', author: 'river_spencer', content: 'My mental health improved drastically', timestamp: '17h ago' },
    { id: '7-35', author: 'ace_peters', content: 'Social media is toxic for recovery', timestamp: '17h ago' },
    { id: '7-36', author: 'phoenix_franklin', content: 'Use it only for messaging if needed', timestamp: '18h ago' },
    { id: '7-37', author: 'theo_stephenson', content: 'You don\'t need it as much as you think', timestamp: '18h ago' },
  ],
  '8': [
    { id: '8-1', author: 'asher_ferguson', content: 'This is the most inspiring post I\'ve ever read', timestamp: '15m ago' },
    { id: '8-2', author: 'axel_reynolds', content: 'Absolutely legendary achievement! Congrats!', timestamp: '30m ago' },
    { id: '8-3', author: 'milo_ellis', content: 'Day 5 here, can\'t wait to be where you are', timestamp: '45m ago' },
    { id: '8-4', author: 'jasper_harper', content: 'What was the timeline for each benefit?', timestamp: '1h ago' },
    { id: '8-5', author: 'felix_fox', content: 'This gives me so much hope. Thank you for sharing', timestamp: '1h ago' },
    { id: '8-6', author: 'leo_alexander22', content: 'Triple digits! That\'s insane. So proud of you', timestamp: '2h ago' },
    { id: '8-7', author: 'ezra_hayes', content: 'How did your personality change?', timestamp: '2h ago' },
    { id: '8-8', author: 'hudson_myers', content: 'Lost weight, got promoted, and dating? This is goals', timestamp: '3h ago' },
    { id: '8-9', author: 'dominic_ford', content: 'When did you start noticing the major changes?', timestamp: '3h ago' },
    { id: '8-10', author: 'tristan_hamilton', content: 'I\'m on day 20 and already feeling different', timestamp: '4h ago' },
    { id: '8-11', author: 'roman_graham', content: 'What was your lowest point before starting?', timestamp: '4h ago' },
    { id: '8-12', author: 'colt_sullivan', content: 'This post is proof that it works. Saving this', timestamp: '5h ago' },
    { id: '8-13', author: 'jax_wallace', content: 'The weight loss is incredible! Did you change diet?', timestamp: '5h ago' },
    { id: '8-14', author: 'dash_woods', content: 'Congratulations brother! You\'re an inspiration', timestamp: '6h ago' },
    { id: '8-15', author: 'knox_kennedy99', content: 'How did you deal with flatlines?', timestamp: '6h ago' },
    { id: '8-16', author: 'west_lawson', content: 'Did confidence come naturally or did you work on it?', timestamp: '7h ago' },
    { id: '8-17', author: 'cade_fields', content: 'Both! The streak gave me foundation, then I built on it', timestamp: '7h ago' },
    { id: '8-18', author: 'lane_freeman', content: '100 days seems impossible but you did it', timestamp: '8h ago' },
    { id: '8-19', author: 'pierce_webb', content: 'What was your morning routine like?', timestamp: '8h ago' },
    { id: '8-20', author: 'crew_tucker', content: 'Cold showers, workout, meditation', timestamp: '9h ago' },
    { id: '8-21', author: 'stetson_porter', content: 'That\'s exactly what I needed to hear', timestamp: '9h ago' },
    { id: '8-22', author: 'boone_hunter', content: 'Did you use any apps or trackers?', timestamp: '10h ago' },
    { id: '8-23', author: 'ridge_hicks', content: 'Just my streak counter and this community', timestamp: '10h ago' },
    { id: '8-24', author: 'bo_crawford', content: 'The dating part gives me hope. I\'ve been alone for years', timestamp: '11h ago' },
    { id: '8-25', author: 'bear_henry', content: 'You\'re not alone anymore. You got us', timestamp: '11h ago' },
    { id: '8-26', author: 'wolf_boyd', content: 'What would you tell your day 1 self?', timestamp: '12h ago' },
    { id: '8-27', author: 'storm_mason88', content: '"It gets so much better. Just don\'t quit"', timestamp: '12h ago' },
    { id: '8-28', author: 'fox_morales', content: 'Screenshotting this for when I struggle', timestamp: '13h ago' },
    { id: '8-29', author: 'hawk_johnston', content: 'How did work performance improve?', timestamp: '13h ago' },
    { id: '8-30', author: 'blaze_dixon', content: 'More focus, energy, and confidence in meetings', timestamp: '14h ago' },
    { id: '8-31', author: 'steel_ramos', content: 'Your boss noticed the change?', timestamp: '14h ago' },
    { id: '8-32', author: 'stone_gilbert', content: 'Everyone noticed. I became a different person', timestamp: '15h ago' },
    { id: '8-33', author: 'blade_cole', content: 'This is the transformation I want', timestamp: '15h ago' },
    { id: '8-34', author: 'maverick_stone', content: 'How many times did you relapse before this streak?', timestamp: '16h ago' },
    { id: '8-35', author: 'hunter_hawkins', content: 'At least 10 times. Each one taught me something', timestamp: '16h ago' },
    { id: '8-36', author: 'ranger_dunn', content: 'That\'s important to hear. Failure is part of success', timestamp: '17h ago' },
    { id: '8-37', author: 'gunner_spencer', content: 'What books or resources helped you?', timestamp: '17h ago' },
    { id: '8-38', author: 'arrow_peters', content: 'Atomic Habits, Can\'t Hurt Me, and this community', timestamp: '18h ago' },
    { id: '8-39', author: 'wilder_franklin', content: 'Added all three to my reading list', timestamp: '18h ago' },
    { id: '8-40', author: 'striker_stephens', content: 'Did you have accountability partners?', timestamp: '19h ago' },
    { id: '8-41', author: 'justice_ferguson', content: 'One close friend who knew my struggle', timestamp: '19h ago' },
    { id: '8-42', author: 'legend_reynolds', content: 'Having support is so important', timestamp: '20h ago' },
    { id: '8-43', author: 'titan_ellis', content: 'You can\'t do it alone. Community matters', timestamp: '20h ago' },
    { id: '8-44', author: 'valor_harper', content: 'What physical changes did you notice?', timestamp: '21h ago' },
    { id: '8-45', author: 'noble_fox77', content: 'Clearer skin, better posture, more muscle definition', timestamp: '21h ago' },
    { id: '8-46', author: 'chief_hayes', content: 'The skin thing is real! Mine improved too', timestamp: '22h ago' },
    { id: '8-47', author: 'major_myers', content: 'Eye contact became easier for me', timestamp: '22h ago' },
    { id: '8-48', author: 'colonel_ford', content: 'Same! I used to avoid eye contact', timestamp: '23h ago' },
    { id: '8-49', author: 'captain_hamilton', content: 'Social anxiety decreased significantly', timestamp: '23h ago' },
    { id: '8-50', author: 'scout_graham', content: 'This post made me believe change is possible', timestamp: '1d ago' },
    { id: '8-51', author: 'marshall_sullivan', content: 'Not just possible - it\'s inevitable if you don\'t quit', timestamp: '1d ago' },
    { id: '8-52', author: 'rebel_wallace', content: 'Day 30 tomorrow. Aiming for 100 like you', timestamp: '1d ago' },
    { id: '8-53', author: 'justice_woods88', content: 'You got this! The next 70 days will fly by', timestamp: '1d ago' },
    { id: '8-54', author: 'maverick_kennedy', content: 'What\'s your next goal?', timestamp: '1d ago' },
    { id: '8-55', author: 'diesel_lawson', content: '180 days, then a full year. Never going back', timestamp: '1d ago' },
    { id: '8-56', author: 'rex_fields', content: 'That\'s the mindset! One day at a time', timestamp: '1d ago' },
    { id: '8-57', author: 'blaze_freeman33', content: 'Forever grateful for posts like this', timestamp: '1d ago' },
    { id: '8-58', author: 'tiger_webb', content: 'You changed lives today with this post', timestamp: '1d ago' },
    { id: '8-59', author: 'wolf_tucker22', content: 'Proud of you man. Keep inspiring others', timestamp: '1d ago' },
    { id: '8-60', author: 'storm_porter', content: 'This community is incredible 💪', timestamp: '1d ago' },
    { id: '8-61', author: 'knight_hunter', content: 'Best support group on the internet', timestamp: '1d ago' },
    { id: '8-62', author: 'duke_hicks55', content: 'We all lift each other up here', timestamp: '1d ago' },
    { id: '8-63', author: 'king_crawford', content: 'Together we\'re stronger 🔥', timestamp: '1d ago' },
    { id: '8-64', author: 'prince_henry', content: 'This is just the beginning for you', timestamp: '1d ago' },
    { id: '8-65', author: 'baron_boyd', content: 'Can\'t wait to post my 100 day update', timestamp: '1d ago' },
    { id: '8-66', author: 'knight_mason', content: 'See you there brother! We\'re all making it', timestamp: '1d ago' },
    { id: '8-67', author: 'dev_chronicles', content: 'Started noticing changes around day 20-30. Energy improved first, then confidence around day 45. The physical changes (weight loss, better skin) came around day 60. Mental clarity peaked around day 80.', timestamp: '1d ago' },
    { id: '8-68', author: 'dominic_ford', content: 'This timeline is so helpful! Saving this.', timestamp: '1d ago' },
    { id: '8-69', author: 'roman_graham', content: 'So it was depression, social anxiety, and zero motivation. Couldn\'t even look people in the eye.', timestamp: '1d ago' },
    { id: '8-70', author: 'dev_chronicles', content: 'Yeah that was me exactly. Rock bottom was the best thing that happened - gave me the push to change.', timestamp: '1d ago' },
    { id: '8-71', author: 'jax_wallace', content: 'Did you count calories or just eat healthy?', timestamp: '1d ago' },
    { id: '8-72', author: 'dev_chronicles', content: 'I tracked macros for the first month, then just ate clean intuitively. Cut out junk food and sugar completely.', timestamp: '1d ago' },
    { id: '8-73', author: 'knox_kennedy99', content: 'The sugar cravings were intense for me', timestamp: '1d ago' },
    { id: '8-74', author: 'west_lawson', content: 'Confidence didn\'t come naturally. I had to force myself to make eye contact and talk to people at first.', timestamp: '1d ago' },
    { id: '8-75', author: 'dev_chronicles', content: 'Exactly! Fake it till you make it actually works. After a month it became natural.', timestamp: '1d ago' },
    { id: '8-76', author: 'pierce_webb', content: 'I needed to hear this. I\'ve been avoiding people.', timestamp: '1d ago' },
    { id: '8-77', author: 'ace_morales99', content: 'This is the motivation I needed today 🙏', timestamp: '1d ago' },
  ],
  '9': [
    { id: '9-1', author: 'luke_bryant', content: 'I deleted Instagram completely. Best decision ever', timestamp: '30m ago' },
    { id: '9-2', author: 'alex_rivera23', content: 'How did you deal with FOMO though?', timestamp: '30m ago' },
    { id: '9-3', author: 'luke_bryant', content: 'First week was hard. But after that I realized I wasn\'t missing anything important. Real friends text me directly.', timestamp: '35m ago' },
    { id: '9-4', author: 'gavin_alexander', content: 'Use content filters and block suggestions', timestamp: '1h ago' },
    { id: '9-5', author: 'wyatt_russell', content: 'Removed all social media from my phone', timestamp: '1h ago' },
    { id: '9-6', author: 'blake_griffin', content: 'The algorithm keeps pushing triggering content', timestamp: '2h ago' },
    { id: '9-7', author: 'alex_rivera23', content: 'Exactly! Even when I click "not interested" it still shows up', timestamp: '2h ago' },
    { id: '9-8', author: 'owen_hayes', content: 'I only use social media on my laptop now. Makes it less accessible.', timestamp: '2h ago' },
    { id: '9-9', author: 'silas_myers', content: 'Deleted TikTok 2 months ago, life is better', timestamp: '3h ago' },
    { id: '9-10', author: 'landon_ford', content: 'Use screen time limits and content restrictions', timestamp: '3h ago' },
    { id: '9-11', author: 'sawyer_hamilton', content: 'The "Not Interested" button doesn\'t work for me either', timestamp: '4h ago' },
    { id: '9-12', author: 'parker_graham', content: 'I keep social media logged out on my phone', timestamp: '4h ago' },
    { id: '9-13', author: 'chase_sullivan', content: 'Explore page is the worst trigger', timestamp: '5h ago' },
    { id: '9-14', author: 'elias_wallace', content: 'Switched to Reddit only, way better control', timestamp: '5h ago' },
    { id: '9-15', author: 'emmett_woods', content: 'Use app blockers during vulnerable times', timestamp: '6h ago' },
    { id: '9-16', author: 'finn_kennedy', content: 'Grayscale mode on my phone helped reduce scrolling', timestamp: '6h ago' },
    { id: '9-17', author: 'rhett_lawson', content: 'Social media is designed to be addictive', timestamp: '7h ago' },
    { id: '9-18', author: 'cash_fields', content: 'I only follow educational accounts now', timestamp: '7h ago' },
    { id: '9-19', author: 'cruz_freeman', content: 'Deleted Snapchat too, it was bad', timestamp: '8h ago' },
    { id: '9-20', author: 'griffin_webb', content: 'The FOMO was hard at first but now I don\'t miss it', timestamp: '8h ago' },
    { id: '9-21', author: 'knox_tucker', content: 'Use parental controls on your own phone', timestamp: '9h ago' },
    { id: '9-22', author: 'kai_porter', content: 'I have my accountability partner manage my restrictions', timestamp: '9h ago' },
    { id: '9-23', author: 'duke_hunter', content: 'The algorithm knows exactly what to show you', timestamp: '10h ago' },
    { id: '9-24', author: 'miles_hicks', content: 'Cold turkey deletion worked for me', timestamp: '10h ago' },
    { id: '9-25', author: 'maddox_crawford', content: '30-day social media detox changed my life', timestamp: '11h ago' },
    { id: '9-26', author: 'brooks_henry', content: 'Use website blockers on all devices', timestamp: '11h ago' },
    { id: '9-27', author: 'beckett_boyd', content: 'Following only friends and family helps', timestamp: '12h ago' },
    { id: '9-28', author: 'king_mason', content: 'Turn off autoplay on all platforms', timestamp: '12h ago' },
    { id: '9-29', author: 'archer_morales', content: 'Delete and reinstall when you need it', timestamp: '13h ago' },
    { id: '9-30', author: 'reed_johnston', content: 'That\'s too much work, just delete permanently', timestamp: '13h ago' },
    { id: '9-31', author: 'braxton_dixon', content: 'Instagram reels are the worst', timestamp: '14h ago' },
    { id: '9-32', author: 'holden_ramos', content: 'Agreed! Endless scrolling is designed to trap you', timestamp: '14h ago' },
    { id: '9-33', author: 'maximus_gilbert', content: 'Use app timers and stick to them', timestamp: '15h ago' },
    { id: '9-34', author: 'zane_stone', content: 'Going outside more helped me forget about social media', timestamp: '15h ago' },
    { id: '9-35', author: 'atlas_hawkins', content: 'Reading replaced scrolling for me', timestamp: '16h ago' },
    { id: '9-36', author: 'jude_dunn', content: 'Best decision: deleting all of it', timestamp: '16h ago' },
    { id: '9-37', author: 'river_spencer', content: 'My mental health improved drastically', timestamp: '17h ago' },
  ],
  '10': [
    { id: '10-1', author: 'benjamin_cooper', content: 'Don\'t be too hard on yourself. Progress isn\'t linear', timestamp: '20m ago' },
    { id: '10-2', author: 'samuel_richardson', content: 'I relapsed 4 times before my current 60 day streak', timestamp: '40m ago' },
    { id: '10-3', author: 'patrick_cox', content: 'Identifying triggers is huge. You\'ve already won by learning', timestamp: '1h ago' },
    { id: '10-4', author: 'alexander_howard', content: 'What are you planning to do differently this time?', timestamp: '1h ago' },
    { id: '10-5', author: 'chris_morales', content: 'Going to schedule my evenings better. Gym at 7pm, dinner, then reading or gaming. No alone time with phone.', timestamp: '1h ago' },
    { id: '10-6', author: 'jack_ward', content: 'Boredom is my trigger too. Started reading books to fight it', timestamp: '2h ago' },
    { id: '10-7', author: 'ryan_torres', content: '22 days is still amazing progress. Don\'t forget that', timestamp: '2h ago' },
    { id: '10-8', author: 'jeremy_peterson', content: 'Every relapse taught me something valuable', timestamp: '3h ago' },
    { id: '10-9', author: 'nicholas_gray', content: 'The fact you\'re analyzing it means you\'re growing', timestamp: '3h ago' },
    { id: '10-10', author: 'walter_ramirez', content: 'Keep a boredom emergency list - activities to do immediately', timestamp: '4h ago' },
    { id: '10-11', author: 'chris_morales', content: 'Good idea! I\'ll make a list tonight.', timestamp: '4h ago' },
    { id: '10-12', author: 'peter_james', content: 'You got this bro. Learn and move forward', timestamp: '4h ago' },
    { id: '10-13', author: 'henry_watson', content: 'Setbacks are part of the journey. Don\'t quit', timestamp: '5h ago' },
    { id: '10-14', author: 'carl_brooks', content: 'I keep a list of things to do when bored on my phone', timestamp: '5h ago' },
    { id: '10-15', author: 'arthur_kelly', content: 'Have you tried scheduling your day in advance?', timestamp: '6h ago' },
    { id: '10-16', author: 'roger_sanders', content: 'Boredom + phone = danger zone for me too', timestamp: '6h ago' },
    { id: '10-17', author: 'joe_price', content: 'The learning is what matters. You\'ll beat this', timestamp: '7h ago' },
    { id: '10-18', author: 'albert_bennett', content: 'I had 5 relapses before hitting 90 days', timestamp: '7h ago' },
    { id: '10-19', author: 'jonathan_wood', content: 'Structure your free time better. That helped me', timestamp: '8h ago' },
    { id: '10-20', author: 'justin_barnes', content: 'You\'re not starting from zero. You learned something huge', timestamp: '8h ago' },
    { id: '10-21', author: 'terry_ross', content: 'Boredom was my biggest enemy too', timestamp: '9h ago' },
    { id: '10-22', author: 'gerald_henderson', content: 'Find a hobby that requires your full attention', timestamp: '9h ago' },
    { id: '10-23', author: 'keith_coleman', content: 'The awareness itself is huge progress', timestamp: '10h ago' },
    { id: '10-24', author: 'samuel_jenkins', content: 'Now you know what to watch for. That\'s powerful', timestamp: '10h ago' },
    { id: '10-25', author: 'willie_perry', content: 'I started gaming to fight boredom urges', timestamp: '11h ago' },
    { id: '10-26', author: 'ralph_powell', content: 'Keep your mind and hands busy', timestamp: '11h ago' },
    { id: '10-27', author: 'lawrence_long', content: 'You\'re going to crush it this time', timestamp: '12h ago' },
    { id: '10-28', author: 'philip_patterson', content: 'Learning from mistakes is the key to success', timestamp: '12h ago' },
    { id: '10-29', author: 'bobby_hughes', content: 'Schedule every hour of your day', timestamp: '13h ago' },
    { id: '10-30', author: 'johnny_flores', content: 'This is part of the process. Keep going', timestamp: '13h ago' },
    { id: '10-31', author: 'randy_washington', content: 'Have a plan for when boredom hits', timestamp: '14h ago' },
    { id: '10-32', author: 'howard_butler', content: 'You made it 22 days. You can do it again', timestamp: '14h ago' },
    { id: '10-33', author: 'eugene_simmons', content: 'Boredom is just an opportunity to build discipline', timestamp: '15h ago' },
    { id: '10-34', author: 'carlos_foster', content: 'I keep gym clothes ready for boredom moments', timestamp: '15h ago' },
    { id: '10-35', author: 'russell_gonzales', content: 'Recognizing patterns is the first step to breaking them', timestamp: '16h ago' },
    { id: '10-36', author: 'bobby_bryant', content: 'Cold showers when bored help me reset', timestamp: '16h ago' },
    { id: '10-37', author: 'victor_alexander', content: 'You\'ve got the self-awareness now', timestamp: '17h ago' },
    { id: '10-38', author: 'ernest_russell', content: 'Fill your schedule with activities', timestamp: '17h ago' },
    { id: '10-39', author: 'phillip_griffin', content: 'Every attempt teaches you something new', timestamp: '18h ago' },
    { id: '10-40', author: 'todd_diaz', content: 'The fact you\'re back here shows your commitment', timestamp: '18h ago' },
    { id: '10-41', author: 'jesse_hayes', content: 'Boredom = time to do something productive', timestamp: '19h ago' },
  ],
  '11': [
    { id: '11-1', author: 'shawn_hamilton', content: 'Lifting weights changed my life too. Best decision', timestamp: '30m ago' },
    { id: '11-2', author: 'clarence_graham', content: 'What\'s your routine look like?', timestamp: '45m ago' },
    { id: '11-3', author: 'jordan_smith88', content: 'Right now I\'m doing Push/Pull/Legs/Rest/Repeat. Compound movements + some isolation. About 45-60min per session.', timestamp: '50m ago' },
    { id: '11-4', author: 'sean_sullivan', content: 'Started PPL split 3 months ago, game changer', timestamp: '1h ago' },
    { id: '11-5', author: 'philip_wallace', content: 'The discipline from gym transfers to everything else', timestamp: '1h ago' },
    { id: '11-6', author: 'johnny_woods', content: 'What time do you usually work out?', timestamp: '2h ago' },
    { id: '11-7', author: 'jordan_smith88', content: '6am before work. Sets the tone for my whole day. If I can do that, I can do anything.', timestamp: '2h ago' },
    { id: '11-8', author: 'earl_kennedy', content: 'Morning workouts set the tone for my whole day too', timestamp: '2h ago' },
    { id: '11-9', author: 'jimmy_parker22', content: 'Gains + mental clarity = unstoppable combo', timestamp: '3h ago' },
    { id: '11-10', author: 'antonio_lawson', content: 'Do you do cardio too or just weights?', timestamp: '3h ago' },
    { id: '11-11', author: 'jordan_smith88', content: '20 min cardio after lifting 3x per week. Nothing crazy. Main focus is lifting heavy.', timestamp: '3h ago' },
    { id: '11-12', author: 'danny_fields', content: 'The confidence boost from lifting is real', timestamp: '4h ago' },
    { id: '11-13', author: 'bryan_freeman', content: 'Started with 3 days, now doing 6. Addicted to the progress', timestamp: '4h ago' },
    { id: '11-14', author: 'tony_webb', content: 'Gym is like meditation for me now', timestamp: '5h ago' },
    { id: '11-15', author: 'luis_tucker', content: 'What\'s your go-to pre-workout?', timestamp: '5h ago' },
    { id: '11-16', author: 'jordan_smith88', content: 'Black coffee and a banana 30min before. Keep it simple.', timestamp: '5h ago' },
    { id: '11-17', author: 'mike_porter', content: 'Push/Pull/Legs or Upper/Lower split?', timestamp: '6h ago' },
    { id: '11-18', author: 'stanley_hunter', content: 'The pump is the best feeling', timestamp: '6h ago' },
    { id: '11-19', author: 'leonard_hicks', content: 'How long until you saw real progress?', timestamp: '7h ago' },
    { id: '11-20', author: 'jordan_smith88', content: 'Felt better immediately. Visible changes around week 3-4. Real transformation after 8 weeks.', timestamp: '7h ago' },
    { id: '11-21', author: 'nathan_crawford', content: 'Consistency is key. I\'m on month 4', timestamp: '7h ago' },
    { id: '11-22', author: 'manuel_henry', content: 'Progressive overload changed everything for me', timestamp: '8h ago' },
    { id: '11-23', author: 'rodney_boyd', content: 'The mental benefits are underrated', timestamp: '8h ago' },
    { id: '11-24', author: 'curtis_mason', content: 'Do you track your lifts?', timestamp: '9h ago' },
    { id: '11-25', author: 'jordan_smith88', content: 'Yeah I use a simple notebook. Write down every set, weight, reps. Helps me progress.', timestamp: '9h ago' },
    { id: '11-26', author: 'norman_morales', content: 'Started tracking and progress doubled', timestamp: '9h ago' },
    { id: '11-27', author: 'allen_kennedy', content: 'Compound movements or isolation?', timestamp: '10h ago' },
    { id: '11-28', author: 'marvin_warren', content: 'Focus on compounds first, then isolation', timestamp: '10h ago' },
    { id: '11-29', author: 'vincent_dixon', content: 'Deadlifts and squats = king exercises', timestamp: '11h ago' },
    { id: '11-30', author: 'glenn_ramos', content: 'The pump addiction is real 💪', timestamp: '11h ago' },
    { id: '11-31', author: 'jeffery_gilbert', content: 'What\'s your favorite workout split?', timestamp: '12h ago' },
    { id: '11-32', author: 'travis_stone', content: 'Rest days are just as important!', timestamp: '12h ago' },
    { id: '11-33', author: 'chad_hawkins', content: 'Sleep + gym + nutrition = gains', timestamp: '13h ago' },
    { id: '11-34', author: 'jacob_dunn', content: 'Form over ego lifting always', timestamp: '13h ago' },
    { id: '11-35', author: 'melvin_perkins', content: 'Progressive overload is the secret', timestamp: '14h ago' },
    { id: '11-36', author: 'alfred_spencer', content: 'Lifting taught me discipline in all areas', timestamp: '14h ago' },
    { id: '11-37', author: 'kyle_peters', content: 'The mental health benefits are huge', timestamp: '15h ago' },
    { id: '11-38', author: 'francis_franklin', content: 'Started 6 months ago, down 30lbs', timestamp: '15h ago' },
    { id: '11-39', author: 'bradley_wright22', content: 'Consistency beats intensity every time', timestamp: '16h ago' },
    { id: '11-40', author: 'jesus_stephens', content: 'The gym saved my life honestly', timestamp: '16h ago' },
    { id: '11-41', author: 'herbert_ferguson', content: 'What\'s your bench/squat/deadlift numbers?', timestamp: '17h ago' },
    { id: '11-42', author: 'jordan_smith88', content: 'Bench 185, Squat 225, Deadlift 275. Not huge but progress!', timestamp: '17h ago' },
    { id: '11-43', author: 'frederick_ford', content: 'Strength gains = confidence gains', timestamp: '17h ago' },
    { id: '11-44', author: 'ray_reynolds', content: 'Do you follow any specific program?', timestamp: '18h ago' },
    { id: '11-45', author: 'joel_ellis', content: 'Been running nSuns, highly recommend', timestamp: '18h ago' },
    { id: '11-46', author: 'edwin_harper', content: 'The routine keeps me accountable', timestamp: '19h ago' },
    { id: '11-47', author: 'don_fox', content: 'Gym = therapy + gains', timestamp: '19h ago' },
    { id: '11-48', author: 'ricky_alexander', content: 'Lost 40lbs and gained confidence', timestamp: '20h ago' },
    { id: '11-49', author: 'marc_hayes55', content: 'Muscle confusion or progressive overload?', timestamp: '20h ago' },
    { id: '11-50', author: 'nathaniel_gardner', content: 'Both have their place in training', timestamp: '21h ago' },
    { id: '11-51', author: 'clifford_wells', content: 'The discipline transfers to recovery journey', timestamp: '21h ago' },
    { id: '11-52', author: 'francis_hart', content: 'Working out kills urges for me', timestamp: '22h ago' },
  ],
  '12': [
    { id: '12-1', author: 'michael_hall', content: 'I\'m on week 3 and sleep quality has been incredible', timestamp: '30m ago' },
    { id: '12-2', author: 'james_allen', content: 'Same! I used to wake up multiple times per night', timestamp: '1h ago' },
    { id: '12-3', author: 'william_young', content: 'How long did it take before you noticed the change?', timestamp: '1h ago' },
    { id: '12-4', author: 'michael_hall', content: 'Around day 14-16 for me. Suddenly I was sleeping through the night.', timestamp: '1h ago' },
    { id: '12-5', author: 'tyler_nguyen', content: 'That\'s encouraging! Only 4 more days then maybe.', timestamp: '1h ago' },
    { id: '12-6', author: 'david_king', content: 'This is one of the best benefits for sure', timestamp: '2h ago' },
    { id: '12-7', author: 'joseph_wright', content: 'Dreams became more vivid for me too', timestamp: '2h ago' },
    { id: '12-8', author: 'thomas_lopez', content: 'My sleep quality improved around day 10', timestamp: '3h ago' },
    { id: '12-9', author: 'charles_hill', content: 'No more late night scrolling was a game changer', timestamp: '3h ago' },
    { id: '12-10', author: 'christopher_scott', content: 'I fall asleep so much faster now', timestamp: '4h ago' },
    { id: '12-11', author: 'daniel_green', content: 'REM sleep quality definitely improved', timestamp: '4h ago' },
    { id: '12-12', author: 'paul_adams', content: 'Used to need 9 hours, now I feel great with 7', timestamp: '5h ago' },
    { id: '12-13', author: 'mark_baker', content: 'Mornings are so much easier now', timestamp: '5h ago' },
    { id: '12-14', author: 'donald_nelson', content: 'I wake up actually feeling rested', timestamp: '6h ago' },
    { id: '12-15', author: 'george_carter', content: 'This was one of the first benefits I noticed', timestamp: '6h ago' },
    { id: '12-16', author: 'kenneth_mitchell', content: 'Sleep tracking app shows huge improvement', timestamp: '7h ago' },
    { id: '12-17', author: 'steven_perez', content: 'No more brain fog in the morning!', timestamp: '7h ago' },
    { id: '12-18', author: 'edward_roberts', content: 'Deep sleep percentage went up significantly', timestamp: '8h ago' },
    { id: '12-19', author: 'brian_turner', content: 'I used to be exhausted all day, not anymore', timestamp: '8h ago' },
    { id: '12-20', author: 'ronald_phillips', content: 'This alone makes it worth it', timestamp: '9h ago' },
    { id: '12-21', author: 'anthony_campbell', content: 'Sleep is so underrated for recovery', timestamp: '9h ago' },
    { id: '12-22', author: 'kevin_parker', content: 'My Fitbit data shows massive improvement', timestamp: '10h ago' },
    { id: '12-23', author: 'jason_evans', content: 'Dreams feel more meaningful now', timestamp: '10h ago' },
    { id: '12-24', author: 'matthew_edwards', content: 'Insomnia completely gone for me', timestamp: '11h ago' },
    { id: '12-25', author: 'gary_collins', content: 'I actually enjoy going to bed now', timestamp: '11h ago' },
    { id: '12-26', author: 'timothy_stewart', content: 'Sleep schedule normalized naturally', timestamp: '12h ago' },
    { id: '12-27', author: 'jose_sanchez', content: 'Melatonin production must be better', timestamp: '12h ago' },
    { id: '12-28', author: 'larry_morris', content: 'Night sweats completely stopped', timestamp: '13h ago' },
    { id: '12-29', author: 'jeffrey_rogers', content: 'Feel like a new person in the mornings', timestamp: '13h ago' },
    { id: '12-30', author: 'frank_reed', content: 'This is one of the best benefits!', timestamp: '14h ago' },
    { id: '12-31', author: 'scott_cook', content: 'Energy levels throughout the day are better', timestamp: '14h ago' },
    { id: '12-32', author: 'eric_morgan', content: 'I wake up before my alarm now', timestamp: '15h ago' },
    { id: '12-33', author: 'stephen_bell', content: 'Quality over quantity for sure', timestamp: '15h ago' },
    { id: '12-34', author: 'andrew_murphy', content: 'This motivates me to keep going', timestamp: '16h ago' },
  ],
  '13': [
    { id: '13-1', author: 'derek_wallace', content: 'Brain fog cleared up around day 30 for me', timestamp: '15m ago' },
    { id: '13-2', author: 'omar_hassan', content: 'Only 5 more days then hopefully. This is brutal.', timestamp: '20m ago' },
    { id: '13-3', author: 'marcus_patterson', content: 'Totally normal. Day 20-40 was foggy for me, then it lifted suddenly', timestamp: '30m ago' },
    { id: '13-4', author: 'travis_cole', content: 'The flatline hits everyone differently', timestamp: '45m ago' },
    { id: '13-5', author: 'omar_hassan', content: 'Good to know it\'s not just me. I thought something was wrong.', timestamp: '50m ago' },
    { id: '13-6', author: 'lucas_barnes', content: 'Your brain is literally rewiring. It takes time.', timestamp: '1h ago' },
    { id: '13-7', author: 'eli_foster', content: 'I felt stupid for like 3 weeks, then BAM - clarity hit', timestamp: '1h ago' },
    { id: '13-8', author: 'silas_reed', content: 'When it clears, it\'s like someone turned the lights on', timestamp: '2h ago' },
    { id: '13-9', author: 'omar_hassan', content: 'That\'s what I\'m hoping for. Can\'t wait to feel normal again.', timestamp: '2h ago' },
    { id: '13-10', author: 'rowan_bryant', content: 'Are you getting enough sleep and exercise?', timestamp: '3h ago' },
    { id: '13-11', author: 'omar_hassan', content: 'Sleep is rough but I\'m working out 4x per week', timestamp: '3h ago' },
    { id: '13-12', author: 'rowan_bryant', content: 'Focus on sleep. That helped my clarity come back faster.', timestamp: '3h ago' },
    { id: '13-13', author: 'colton_mills', content: 'Cut out sugar and caffeine too. Made a huge difference.', timestamp: '4h ago' },
    { id: '13-14', author: 'omar_hassan', content: 'I drink way too much coffee. Maybe I should cut back.', timestamp: '4h ago' },
    { id: '13-15', author: 'preston_hunt', content: 'Stay hydrated too. Dehydration makes brain fog worse.', timestamp: '5h ago' },
    { id: '13-16', author: 'jude_morrison', content: 'I started taking omega-3 supplements. Helped a lot.', timestamp: '5h ago' },
    { id: '13-17', author: 'nash_palmer', content: 'Cold showers helped my mental clarity', timestamp: '6h ago' },
    { id: '13-18', author: 'omar_hassan', content: 'I\'ll try cold showers tomorrow morning', timestamp: '6h ago' },
    { id: '13-19', author: 'zeke_bennett', content: 'Reading instead of scrolling helped me too', timestamp: '7h ago' },
    { id: '13-20', author: 'finn_russell', content: 'Be patient with yourself. Your brain needs time.', timestamp: '7h ago' },
    { id: '13-21', author: 'omar_hassan', content: 'Thanks everyone. This community is the best 🙏', timestamp: '8h ago' },
    { id: '13-22', author: 'tate_coleman', content: 'Day 60 now and my focus is incredible', timestamp: '8h ago' },
    { id: '13-23', author: 'cade_jenkins', content: 'Meditation helped speed up the process for me', timestamp: '9h ago' },
    { id: '13-24', author: 'omar_hassan', content: 'I should probably start meditating', timestamp: '9h ago' },
    { id: '13-25', author: 'cade_jenkins', content: 'Just 10 minutes a day. Use Headspace or Calm.', timestamp: '9h ago' },
    { id: '13-26', author: 'reid_powell', content: 'The improvement comes in waves, not linear', timestamp: '10h ago' },
    { id: '13-27', author: 'knox_henderson', content: 'One day you\'ll wake up and just feel... clear', timestamp: '10h ago' },
    { id: '13-28', author: 'omar_hassan', content: 'Looking forward to that day', timestamp: '11h ago' },
  ],
  '14': [
    { id: '14-1', author: 'levi_richards', content: 'I told my partner on day 45. She was supportive and it brought us closer.', timestamp: '10m ago' },
    { id: '14-2', author: 'adrian_costa', content: 'How did you start the conversation?', timestamp: '15m ago' },
    { id: '14-3', author: 'levi_richards', content: 'I just said "There\'s something I need to tell you about my past." Then explained my journey and progress.', timestamp: '20m ago' },
    { id: '14-4', author: 'adrian_costa', content: 'Were you worried she\'d leave?', timestamp: '25m ago' },
    { id: '14-5', author: 'levi_richards', content: 'Terrified. But I realized if she can\'t handle my truth, she\'s not the right person.', timestamp: '30m ago' },
    { id: '14-6', author: 'adrian_costa', content: 'That\'s a good way to look at it. Thanks man.', timestamp: '35m ago' },
    { id: '14-7', author: 'blake_simmons', content: 'I told my girlfriend on day 30. She appreciated the honesty.', timestamp: '40m ago' },
    { id: '14-8', author: 'austin_ward', content: 'Honesty is always better than hiding it', timestamp: '45m ago' },
    { id: '14-9', author: 'garrett_hayes', content: 'My girlfriend found out on her own and it was way worse. Be honest.', timestamp: '1h ago' },
    { id: '14-10', author: 'adrian_costa', content: 'Damn, that must have been rough. How did you recover from that?', timestamp: '1h ago' },
    { id: '14-11', author: 'garrett_hayes', content: 'Lots of communication and therapy. Took 6 months to rebuild trust.', timestamp: '1h ago' },
    { id: '14-12', author: 'cole_murphy', content: 'Choose a calm moment when you both have time to talk', timestamp: '2h ago' },
    { id: '14-13', author: 'adrian_costa', content: 'Good advice. Not during dinner or when she\'s stressed.', timestamp: '2h ago' },
    { id: '14-14', author: 'paxton_kelly', content: 'Frame it as growth. You\'re not that person anymore.', timestamp: '3h ago' },
    { id: '14-15', author: 'sawyer_price', content: 'Emphasize that you\'re telling her because you love and trust her', timestamp: '3h ago' },
    { id: '14-16', author: 'adrian_costa', content: 'I do love her. That\'s why I want to be honest.', timestamp: '3h ago' },
    { id: '14-17', author: 'tanner_brooks', content: 'Don\'t go into graphic details. Keep it high level.', timestamp: '4h ago' },
    { id: '14-18', author: 'brock_sanders', content: 'Yeah, tell her about the recovery, not the addiction', timestamp: '4h ago' },
    { id: '14-19', author: 'adrian_costa', content: 'Good point. Focus on the positive changes.', timestamp: '4h ago' },
    { id: '14-20', author: 'ridge_watson', content: 'My wife was my biggest support after I told her', timestamp: '5h ago' },
    { id: '14-21', author: 'dash_cooper', content: 'Give her time to process. Don\'t expect immediate response.', timestamp: '5h ago' },
    { id: '14-22', author: 'adrian_costa', content: 'I\'m planning to tell her this weekend. Wish me luck.', timestamp: '6h ago' },
    { id: '14-23', author: 'levi_richards', content: 'You got this bro! Update us after', timestamp: '6h ago' },
    { id: '14-24', author: 'blake_simmons', content: 'Rooting for you man 💪', timestamp: '7h ago' },
    { id: '14-25', author: 'garrett_hayes', content: 'Honesty is the foundation of a strong relationship', timestamp: '7h ago' },
    { id: '14-26', author: 'cole_murphy', content: 'Being vulnerable is strength, not weakness', timestamp: '8h ago' },
    { id: '14-27', author: 'paxton_kelly', content: 'She\'ll respect you more for being honest', timestamp: '8h ago' },
    { id: '14-28', author: 'sawyer_price', content: 'The right person will support your journey', timestamp: '9h ago' },
    { id: '14-29', author: 'tanner_brooks', content: 'If she leaves, she wasn\'t meant to be there', timestamp: '9h ago' },
    { id: '14-30', author: 'brock_sanders', content: 'But chances are she\'ll be understanding', timestamp: '10h ago' },
    { id: '14-31', author: 'ridge_watson', content: 'Most people are more understanding than we think', timestamp: '10h ago' },
    { id: '14-32', author: 'dash_cooper', content: 'Communication is everything in relationships', timestamp: '11h ago' },
    { id: '14-33', author: 'adrian_costa', content: 'This thread really helped. Thank you all 🙏', timestamp: '11h ago' },
    { id: '14-34', author: 'knox_anderson', content: 'We\'re all in this together brother', timestamp: '12h ago' },
    { id: '14-35', author: 'crew_thompson', content: 'Let us know how it goes!', timestamp: '12h ago' },
    { id: '14-36', author: 'stetson_garcia', content: 'Sending positive vibes your way', timestamp: '13h ago' },
    { id: '14-37', author: 'boone_martinez', content: 'Honesty will set you free', timestamp: '13h ago' },
    { id: '14-38', author: 'bear_rodriguez', content: 'You\'re making the right choice', timestamp: '14h ago' },
    { id: '14-39', author: 'wolf_wilson', content: 'Proud of you for having the courage', timestamp: '14h ago' },
    { id: '14-40', author: 'storm_moore', content: 'This is what real love looks like', timestamp: '15h ago' },
    { id: '14-41', author: 'fox_taylor', content: 'Trust the process and trust yourself', timestamp: '15h ago' },
    { id: '14-42', author: 'hawk_thomas', content: 'You\'ve got an entire community behind you', timestamp: '16h ago' },
    { id: '14-43', author: 'blaze_jackson', content: 'Honesty is always the best policy', timestamp: '16h ago' },
    { id: '14-44', author: 'steel_white', content: 'Looking forward to your update post!', timestamp: '17h ago' },
    { id: '14-45', author: 'stone_harris', content: 'You\'re going to feel so much lighter after', timestamp: '17h ago' },
  ],
};
